// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "dodger":return img`
........................
.....ffff...............
...fff22fff.............
..fff2222fff............
.fffeeeeeefff...........
.ffe222222eef...........
.fe2ffffff2ef...........
.ffffeeeeffff...........
ffefbf44fbfeff..........
fee41fddf14eef..........
.ffffdddddeef...........
fddddf444eef............
fbbbbf2222f4e...........
fbbbbf2222fd4...........
.fccf45544f44...........
..ffffffff..............
....ff..ff..............
........................
........................
........................
........................
........................
........................
........................
`;
            case "image1":
            case "rock":return img`
. . . . . c c b b b . . . . . . 
. . . . c b d d d d b . . . . . 
. . . . c d d d d d d b b . . . 
. . . . c d d d d d d d d b . . 
. . . c b b d d d d d d d b . . 
. . . c b b d d d d d d d b . . 
. c c c c b b b b d d d b b b . 
. c d d b c b b b b b b b b d b 
c b b d d d b b b b b d d b d b 
c c b b d d d d d d d b b b d c 
c b c c c b b b b b b b d d c c 
c c b b c c c c b d d d b c c b 
. c c c c c c c c c c c b b b b 
. . c c c c c b b b b b b b c . 
. . . . . . c c b b b b c c . . 
. . . . . . . . c c c c . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
